image: docker:git

services:
  - docker:dind

build:
  stage: build
  before_script:
    - echo $GOOGLE_CLOUD_ACCOUNT | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - cd src
    - docker-compose build
    - docker-compose push