stages:
  - build
  - deploy

build_services:
  image: docker:git
  services:
    - docker:dind
  stage: build
  before_script:
    - echo $GOOGLE_CLOUD_ACCOUNT | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - cd src
    - docker-compose build identity-api basket-api catalog-api ordering-api payment-api webhooks-api
    - docker push gcr.io/pelagic-bastion-359618/identity.api:latest
    - docker push gcr.io/pelagic-bastion-359618/basket.api:latest
    - docker push gcr.io/pelagic-bastion-359618/catalog.api:latest
    - docker push gcr.io/pelagic-bastion-359618/ordering.api:latest
    - docker push gcr.io/pelagic-bastion-359618/payment.api:latest
    - docker push gcr.io/pelagic-bastion-359618/webhooks.api:latest
  
build_web:
  image: docker:git
  services:
    - docker:dind
  stage: build
  before_script:
    - echo $GOOGLE_CLOUD_ACCOUNT | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - cd src
    - docker-compose build webhooks-client webmvc webspa webstatus
    - docker push gcr.io/pelagic-bastion-359618/webhooks.client:latest
    - docker push gcr.io/pelagic-bastion-359618/webmvc:latest
    - docker push gcr.io/pelagic-bastion-359618/webspa:latest
    - docker push gcr.io/pelagic-bastion-359618/webstatus:latest
  
build_dockerhub:
  image: docker:git
  services:
    - docker:dind
  when: manual
  stage: build
  before_script:
    - echo $GOOGLE_CLOUD_ACCOUNT | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - cd src
    - docker-compose build seq nosqldata basketdata rabbitmq mobileshoppingapigw webshoppingapigw
    - docker push gcr.io/pelagic-bastion-359618/seq:latest
    - docker push gcr.io/pelagic-bastion-359618/mongo:latest
    - docker push gcr.io/pelagic-bastion-359618/redis:latest
    - docker push gcr.io/pelagic-bastion-359618/rabbitmq:latest
    - docker push gcr.io/pelagic-bastion-359618/mobileshoppingapigw:latest
    - docker push gcr.io/pelagic-bastion-359618/webshoppingapigw:latest

build_apigw:
  image: docker:git
  services:
    - docker:dind
  stage: build
  before_script:
    - echo $GOOGLE_CLOUD_ACCOUNT | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - cd src
    - docker-compose build ordering-backgroundtasks mobileshoppingagg webshoppingagg ordering-signalrhub
    - docker push gcr.io/pelagic-bastion-359618/ordering.backgroundtasks:latest
    - docker push gcr.io/pelagic-bastion-359618/mobileshoppingagg:latest
    - docker push gcr.io/pelagic-bastion-359618/webshoppingagg:latest
    - docker push gcr.io/pelagic-bastion-359618/ordering.signalrhub:latest

deploy_app:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - aws ec2 start-instances --instance-ids $MASTER_ID
    - aws ec2 start-instances --instance-ids $NODE1_ID
    - aws ec2 start-instances --instance-ids $NODE2_ID
    - sleep 20s
    - yes | scp -i $DEPLOY_PAIR ./Master_Files/docker-compose.yml ec2-user@$PUBLIC_IP:/home/docker_files
    - yes | scp -i $DEPLOY_PAIR ./Master_Files/eShopOnContainers/mobileshopping/envoy.yaml ec2-user@$PUBLIC_IP:/home/docker_files/mobileshopping
    - yes | scp -i $DEPLOY_PAIR ./Master_Files/eShopOnContainers/webshopping/envoy.yaml ec2-user@$PUBLIC_IP:/home/docker_files/webshopping
    - aws ssm send-command --instance-ids $MASTER_ID --document-name "DeployDockerStack"

