version: '3.4'

services:

  seq:
    image: gcr.io/pelagic-bastion-359618/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  nosqldata:
    image: gcr.io/pelagic-bastion-359618/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - eshop-nosqldata:/data/db

  basketdata:
    image: gcr.io/pelagic-bastion-359618/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - eshop-basketdata:/data

  rabbitmq:
    image: gcr.io/pelagic-bastion-359618/rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"

  identity-api:
    image: gcr.io/pelagic-bastion-359618/identity.api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://54.163.177.83:5104
      - XamarinCallback=http://54.163.177.83:5105/xamarincallback
      - ConnectionString=Server=tcp:eshopdb.cxnku9kerzxd.us-east-1.rds.amazonaws.com,5433;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass2word
      - MvcClient=http://54.163.177.83:5100
      - BasketApiClient=http://54.163.177.83:5103
      - OrderingApiClient=http://54.163.177.83i:5102
      - MobileShoppingAggClient=http://54.163.177.83:5120
      - WebShoppingAggClient=http://54.163.177.83:5121
      - WebhooksApiClient=http://54.163.177.83:5113
      - WebhooksWebClient=http://54.163.177.83:5114
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
    ports:
      - "5105:80"


  basket-api:
    image: gcr.io/pelagic-bastion-359618/basket.api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=basketdata
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://54.163.177.83:5105
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - UseLoadTest=False
      - PATH_BASE=/basket-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5103:80"
      - "9103:81"
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image:  gcr.io/pelagic-bastion-359618/catalog.api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=tcp:eshopdb.cxnku9kerzxd.us-east-1.rds.amazonaws.com,5433;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass2word
      - PicBaseUrl=http://54.163.177.83:5101/api/v1/catalog/items/[0]/pic/
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/catalog-api
    ports:
      - "5101:80"
      - "9101:81"
    depends_on:
      - rabbitmq

  ordering-api:
    image: gcr.io/pelagic-bastion-359618/ordering.api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=tcp:eshopdb.cxnku9kerzxd.us-east-1.rds.amazonaws.com,5433;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass2word
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://54.163.177.83:5105
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - UseLoadTest=False
      - Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ=Verbose
      - Serilog__MinimumLevel__Override__ordering-api=Verbose
      - PATH_BASE=/ordering-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5102:80"
      - "9102:81"
    depends_on:
      - rabbitmq

  ordering-backgroundtasks:
    image: gcr.io/pelagic-bastion-359618/ordering.backgroundtasks:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=tcp:eshopdb.cxnku9kerzxd.us-east-1.rds.amazonaws.com,5433;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass2word
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - GracePeriodTime=1
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - UseLoadTest=False
      - Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ=Verbose
    ports:
      - "5111:80"
    depends_on:
      - rabbitmq

  payment-api:
    image: gcr.io/pelagic-bastion-359618/payment.api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - Serilog__MinimumLevel__Override__payment-api.IntegrationEvents.EventHandling=Verbose
      - Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ=Verbose
    ports:
      - "5108:80"
    depends_on:
      - rabbitmq

  webhooks-api:
    image: gcr.io/pelagic-bastion-359618/webhooks.api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=tcp:eshopdb.cxnku9kerzxd.us-east-1.rds.amazonaws.com,5433;Database=Microsoft.eShopOnContainers.Services.WebhooksDb;User Id=sa;Password=Pass2word
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://54.163.177.83:5105
    ports:
      - "5113:80"

  mobileshoppingapigw:
    image: gcr.io/pelagic-bastion-359618/mobileshoppingapigw:latest
    volumes:
      - ./eShopOnContainers/mobileshopping:/etc/envoy
    ports:
    - "5200:80"
    - "15200:8001"

  mobileshoppingagg:
    image: gcr.io/pelagic-bastion-359618/mobileshoppingagg:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket-api
      - urls__catalog=http://catalog-api
      - urls__orders=http://ordering-api
      - urls__identity=http://identity-api
      - urls__grpcBasket=http://basket-api:81
      - urls__grpcCatalog=http://catalog-api:81
      - urls__grpcOrdering=http://ordering-api:81
      - CatalogUrlHC=http://catalog-api/hc
      - OrderingUrlHC=http://ordering-api/hc
      - IdentityUrlHC=http://identity-api/hc
      - BasketUrlHC=http://basket-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - IdentityUrlExternal=http://54.163.177.83:5105
    ports:
      - "5120:80"
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: gcr.io/pelagic-bastion-359618/webshoppingagg:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket-api
      - urls__catalog=http://catalog-api
      - urls__orders=http://ordering-api
      - urls__identity=http://identity-api
      - urls__grpcBasket=http://basket-api:81
      - urls__grpcCatalog=http://catalog-api:81
      - urls__grpcOrdering=http://ordering-api:81
      - CatalogUrlHC=http://catalog-api/hc
      - OrderingUrlHC=http://ordering-api/hc
      - IdentityUrlHC=http://identity-api/hc
      - BasketUrlHC=http://basket-api/hc
      - PaymentUrlHC=http://payment-api/hc
      - IdentityUrlExternal=http://54.163.177.83:5105
    ports:
      - "5121:80"
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: gcr.io/pelagic-bastion-359618/ordering.signalrhub:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - identityUrl=http://identity-api
    ports:
      - "5112:80"
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: gcr.io/pelagic-bastion-359618/webstatus:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://webmvc/hc
      - HealthChecksUI__HealthChecks__1__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webspa/hc
      - HealthChecksUI__HealthChecks__2__Name=Web Shopping Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://webshoppingagg/hc
      - HealthChecksUI__HealthChecks__3__Name=Mobile Shopping Aggregator HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://mobileshoppingagg/hc
      - HealthChecksUI__HealthChecks__4__Name=Ordering HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://ordering-api/hc
      - HealthChecksUI__HealthChecks__5__Name=Basket HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://basket-api/hc
      - HealthChecksUI__HealthChecks__6__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__6__Uri=http://catalog-api/hc
      - HealthChecksUI__HealthChecks__7__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__7__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__8__Name=Payments HTTP Check
      - HealthChecksUI__HealthChecks__8__Uri=http://payment-api/hc
      - HealthChecksUI__HealthChecks__9__Name=Ordering SignalRHub HTTP Check
      - HealthChecksUI__HealthChecks__9__Uri=http://ordering-signalrhub/hc
      - HealthChecksUI__HealthChecks__10__Name=Ordering HTTP Background Check
      - HealthChecksUI__HealthChecks__10__Uri=http://ordering-backgroundtasks/hc
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
    ports:
      - "5107:80"

  webspa:
    image: gcr.io/pelagic-bastion-359618/webspa:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://54.163.177.83:5105
      - PurchaseUrl=http://54.163.177.83:5202
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - SignalrHubUrl=http://54.163.177.83:5202
    ports:
      - "5104:80"
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: gcr.io/pelagic-bastion-359618/webmvc:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PurchaseUrl=http://webshoppingapigw
      - IdentityUrl=http://54.163.177.83:5105
      - SignalrHubUrl=http://54.163.177.83:5202
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=DOCKER_SWARM
      - UseLoadTest=False
    ports:
      - "5100:80"
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooks-client:
    image: gcr.io/pelagic-bastion-359618/webhooks.client:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Token=6168DB8D-DC58-4094-AF24-483278923590      # Webhooks are registered with this token (any value is valid) but the client won't check it
      - IdentityUrl=http://54.163.177.83:5105
      - CallBackUrl=http://54.163.177.83:5114
      - WebhooksUrl=http://webhooks-api
      - SelfUrl=http://webhooks-client/
    ports:
      - "5114:80"
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: gcr.io/pelagic-bastion-359618/webshoppingapigw:latest
    volumes:
      - ./eShopOnContainers/webshopping:/etc/envoy
    ports:
    - "5202:80"
    - "15202:8001"
volumes:
  eshop-nosqldata:
    external: false
  eshop-basketdata:
    external: false

