version: '3.4'

services:

  seq:
    image: gcr.io/eshop-infrastructure/seq${TAG}
    build:
      context: .
      dockerfile: DockerHub_Images/seq/Dockerfile

  nosqldata:
    image: gcr.io/eshop-infrastructure/mongo${TAG}
    build:
      context: .
      dockerfile: DockerHub_Images/nosqldata/Dockerfile

  basketdata:
    image: gcr.io/eshop-infrastructure/redis${TAG}
    build:
      context: .
      dockerfile: DockerHub_Images/basketdata/Dockerfile

  rabbitmq:
    image: gcr.io/eshop-infrastructure/rabbitmq${TAG}
    build:
      context: .
      dockerfile: DockerHub_Images/rabbitmq/Dockerfile

  identityapi:
    image: gcr.io/eshop-infrastructure/identity.api${TAG}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  basketapi:
    image: gcr.io/eshop-infrastructure/basket.api${TAG}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalogapi:
    image: gcr.io/eshop-infrastructure/catalog.api${TAG}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  orderingapi:
    image: gcr.io/eshop-infrastructure/orderingapi${TAG}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq

  orderingbackgroundtasks:
    image: gcr.io/eshop-infrastructure/ordering.backgroundtasks${TAG}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  paymentapi:
    image: gcr.io/eshop-infrastructure/paymentapi${TAG}
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq

  webhooksapi:
    image: gcr.io/eshop-infrastructure/webhooks.api${TAG}
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

  mobileshoppingapigw:
    image: gcr.io/eshop-infrastructure/mobileshoppingapigw${TAG}
    build:
      context: .
      dockerfile: DockerHub_Images/mobileshoppingapigw/Dockerfile

  mobileshoppingagg:
    image: gcr.io/eshop-infrastructure/mobileshoppingagg${TAG}
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - orderingapi
      - catalog-api
      - basket-api

  webshoppingagg:
    image: gcr.io/eshop-infrastructure/webshoppingagg${TAG}
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - orderingapi
      - catalog-api
      - basket-api

  orderingsignalrhub:
    image: gcr.io/eshop-infrastructure/ordering.signalrhub${TAG}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - orderingapi
      - catalog-api
      - basket-api

  webstatus:
    image: gcr.io/eshop-infrastructure/webstatus${TAG}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: gcr.io/eshop-infrastructure/webspa${TAG}
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12.0}
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: gcr.io/eshop-infrastructure/webmvc${TAG}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooksclient:
    image: gcr.io/eshop-infrastructure/webhooks.client${TAG}
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: gcr.io/eshop-infrastructure/webshoppingapigw${TAG}
    build:
      context: .
      dockerfile: DockerHub_Images/webshoppingapigw/Dockerfile
