version: '3.4'

services:

  seq:
    image: gcr.io/eshop-infrastructure/seq:1
    build:
      context: .
      dockerfile: DockerHub_Images/seq/Dockerfile

  nosqldata:
    image: gcr.io/eshop-infrastructure/mongo:1
    build:
      context: .
      dockerfile: DockerHub_Images/nosqldata/Dockerfile

  basketdata:
    image: gcr.io/eshop-infrastructure/redis:1
    build:
      context: .
      dockerfile: DockerHub_Images/basketdata/Dockerfile

  rabbitmq:
    image: gcr.io/eshop-infrastructure/rabbitmq:1
    build:
      context: .
      dockerfile: DockerHub_Images/rabbitmq/Dockerfile

  identity-api:
    image: gcr.io/eshop-infrastructure/identity.api:1
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  basket-api:
    image: gcr.io/eshop-infrastructure/basket.api:1
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image: gcr.io/eshop-infrastructure/catalog.api:1
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-api:
    image: gcr.io/eshop-infrastructure/ordering.api:1
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-backgroundtasks:
    image: gcr.io/eshop-infrastructure/ordering.backgroundtasks:1
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  payment-api:
    image: gcr.io/eshop-infrastructure/payment.api:1
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq

  webhooks-api:
    image: gcr.io/eshop-infrastructure/webhooks.api:1
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

  mobileshoppingapigw:
    image: gcr.io/eshop-infrastructure/mobileshoppingapigw:1
    build:
      context: .
      dockerfile: DockerHub_Images/mobileshoppingapigw/Dockerfile

  mobileshoppingagg:
    image: gcr.io/eshop-infrastructure/mobileshoppingagg:1
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: gcr.io/eshop-infrastructure/webshoppingagg:1
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: gcr.io/eshop-infrastructure/ordering.signalrhub:1
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: gcr.io/eshop-infrastructure/webstatus:1
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: gcr.io/eshop-infrastructure/webspa:1
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12.0}
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: gcr.io/eshop-infrastructure/webmvc:1
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooks-client:
    image: gcr.io/eshop-infrastructure/webhooks.client:1
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: gcr.io/eshop-infrastructure/webshoppingapigw:1
    build:
      context: .
      dockerfile: DockerHub_Images/webshoppingapigw/Dockerfile
