version: '3.4'

services:

  seq:
    image: gcr.io/pelagic-bastion-359618/seq:latest
    build:
      context: .
      dockerfile: DockerHub_Images/seq/Dockerfile

  nosqldata:
    image: gcr.io/pelagic-bastion-359618/mongo:latest
    build:
      context: .
      dockerfile: DockerHub_Images/nosqldata/Dockerfile

  basketdata:
    image: gcr.io/pelagic-bastion-359618/redis:latest
    build:
      context: .
      dockerfile: DockerHub_Images/basketdata/Dockerfile

  rabbitmq:
    image: gcr.io/pelagic-bastion-359618/rabbitmq:latest
    build:
      context: .
      dockerfile: DockerHub_Images/rabbitmq/Dockerfile

  identity-api:
    image: gcr.io/pelagic-bastion-359618/identity.api:latest
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  basket-api:
    image: gcr.io/pelagic-bastion-359618/basket.api:latest
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image: gcr.io/pelagic-bastion-359618/catalog.api:latest
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-api:
    image: gcr.io/pelagic-bastion-359618/ordering.api:latest
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-backgroundtasks:
    image: gcr.io/pelagic-bastion-359618/ordering.backgroundtasks:latest
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  payment-api:
    image: gcr.io/pelagic-bastion-359618/payment.api:latest
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq

  webhooks-api:
    image: gcr.io/pelagic-bastion-359618/webhooks.api:latest
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

  mobileshoppingapigw:
    image: gcr.io/pelagic-bastion-359618/mobileshoppingapigw:latest
    build:
      context: .
      dockerfile: DockerHub_Images/mobileshoppingapigw/Dockerfile

  mobileshoppingagg:
    image: gcr.io/pelagic-bastion-359618/mobileshoppingagg:latest
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: gcr.io/pelagic-bastion-359618/webshoppingagg:latest
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: gcr.io/pelagic-bastion-359618/ordering.signalrhub:latest
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: gcr.io/pelagic-bastion-359618/webstatus:latest
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: gcr.io/pelagic-bastion-359618/webspa:latest
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12.0}
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: gcr.io/pelagic-bastion-359618/webmvc:latest
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooks-client:
    image: gcr.io/pelagic-bastion-359618/webhooks.client:latest
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: gcr.io/pelagic-bastion-359618/webshoppingapigw:latest
    build:
      context: .
      dockerfile: DockerHub_Images/webshoppingapigw/Dockerfile
