version: '3.4'

services:

  seq:
    image: gcr.io/eshop-infrastructure/seq:main.${HASH}
    build:
      context: .
      dockerfile: DockerHub_Images/seq/Dockerfile

  nosqldata:
    image: gcr.io/eshop-infrastructure/mongo:main.${HASH}
    build:
      context: .
      dockerfile: DockerHub_Images/nosqldata/Dockerfile

  basketdata:
    image: gcr.io/eshop-infrastructure/redis:main.${HASH}
    build:
      context: .
      dockerfile: DockerHub_Images/basketdata/Dockerfile

  rabbitmq:
    image: gcr.io/eshop-infrastructure/rabbitmq:main.${HASH}
    build:
      context: .
      dockerfile: DockerHub_Images/rabbitmq/Dockerfile

  identityapi:
    image: gcr.io/eshop-infrastructure/identity.api:main.${HASH}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  basketapi:
    image: gcr.io/eshop-infrastructure/basket.api:main.${HASH}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identityapi
      - rabbitmq

  catalogapi:
    image: gcr.io/eshop-infrastructure/catalog.api:main.${HASH}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  orderingapi:
    image: gcr.io/eshop-infrastructure/orderingapi:main.${HASH}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq

  orderingbackgroundtasks:
    image: gcr.io/eshop-infrastructure/ordering.backgroundtasks:main.${HASH}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  paymentapi:
    image: gcr.io/eshop-infrastructure/paymentapi:main.${HASH}
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq

  webhooksapi:
    image: gcr.io/eshop-infrastructure/webhooks.api:main.${HASH}
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

  mobileshoppingapigw:
    image: gcr.io/eshop-infrastructure/mobileshoppingapigw:main.${HASH}
    build:
      context: .
      dockerfile: DockerHub_Images/mobileshoppingapigw/Dockerfile

  mobileshoppingagg:
    image: gcr.io/eshop-infrastructure/mobileshoppingagg:main.${HASH}
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identityapi
      - rabbitmq
      - orderingapi
      - catalogapi
      - basketapi

  webshoppingagg:
    image: gcr.io/eshop-infrastructure/webshoppingagg:main.${HASH}
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identityapi
      - rabbitmq
      - orderingapi
      - catalogapi
      - basketapi

  orderingsignalrhub:
    image: gcr.io/eshop-infrastructure/ordering.signalrhub:main.${HASH}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - identityapi
      - rabbitmq
      - orderingapi
      - catalogapi
      - basketapi

  webstatus:
    image: gcr.io/eshop-infrastructure/webstatus:main.${HASH}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: gcr.io/eshop-infrastructure/webspa:main.${HASH}
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12.0}
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: gcr.io/eshop-infrastructure/webmvc:main.${HASH}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooksclient:
    image: gcr.io/eshop-infrastructure/webhooks.client:main.${HASH}
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: gcr.io/eshop-infrastructure/webshoppingapigw:main.${HASH}
    build:
      context: .
      dockerfile: DockerHub_Images/webshoppingapigw/Dockerfile
